- models/Book.js
Added publication date on book model.
> feature: added publication date

- .vscode/settings.json
- controllers/admin.controller.js
- controllers/book.contoller.js
- models/Admin.js
- routers/api/admin/index.js
- routers/api/book/index.js
Created admin model & router files.
> core: admin model

- controllers/user.controller.js
- plugins/auth.js
- routers/api/book/index.js
- routers/api/user/index.js
- utils/jwt.js
> feature: jwt prehandler

- controllers/book.contoller.js
- controllers/user.controller.js
- models/Book.js
- plugins/error-handler.js
- routers/api/user/index.js
- server.js
Added error handler on fastify instance and implemented.
> feat: error handler

- api/serverless.js
- controllers/book.contoller.js
- controllers/category.controller.js
- controllers/user.controller.js
- models/Category.js
- package.json
- routers/api/category/index.js
- routers/api/user/index.js
- vercel.json
> category and sub category added

- controllers/user.controller.js
- routers/api/user/index.js
- vercel.json
> feature: pagination

- controllers/book.contoller.js
- controllers/category.controller.js
- routers/api/category/index.js
> added paginate to book and category

- models/User.js
> feat: User birthdate fix 

- routers/api/book/index.js
> delete and get book function added

- controllers/user.controller.js
- routers/api/user/index.js
#27 adding user filter and sort
> feat: user filter

- api/serverless.js
- controllers/user.controller.js
- routers/api/admin/index.js
> updated: get->post

- api/serverless.js
- controllers/admin.controller.js
- controllers/category.controller.js
- routers/api/admin/index.js
- routers/api/category/index.js
> added: getCategory

- controllers/author.controller.js
- controllers/category.controller.js
- models/Author.js
- routers/api/author/index.js
- routers/api/category/index.js
- routers/api/file/index.js
> feature: Author model, controller and route 

- controllers/book.contoller.js
- models/Book.js
#39  added summary, format and isfeatured fields
> added summary, format and isfeatured fields

- controllers/book.contoller.js
> category array

- controllers/author.controller.js
- models/Author.js
- routers/api/author/index.js
> feature: author fix

- controllers/admin.controller.js
- controllers/author.controller.js
- controllers/book.contoller.js
- controllers/user.controller.js
- models/Book.js
> Fixed: return document object instead of whole result

- controllers/book.contoller.js
#48 
added following filters:
- by category
- by author
- by format
> added filters

- controllers/book.contoller.js
> added like filter

- controllers/review.controller.js
- models/Review.js
- routers/api/book/index.js
- routers/api/review/index.js
- created review model
- created review.controller
- created review routes
> created review model controller routes

- controllers/category.controller.js
- controllers/collection.controller.js
- models/Collection.js
- routers/api/category/index.js
- routers/api/collection/index.js
removed auth from get request in book route
> removed auth from get request in book route

- controllers/review.controller.js
- routers/api/category/index.js
fixed review controller and removed auth from getCategory
> fixed review controller and remove auth from getCategory

- controllers/book.contoller.js
- controllers/review.controller.js
- models/Book.js
- routers/api/book/index.js
added increase and decrease love functinos and routes
> added increase and decrease love functinos and routes

- controllers/collection.controller.js
- models/Collection.js
- routers/api/collection/index.js
> get collection by UserId

- controllers/category.controller.js
- controllers/collection.controller.js
created categorys parent:null filter
> created categorys parent:null filter
